use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(CrrTxnDtl::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(CrrTxnDtl::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::CompanyCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::StoreCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::TerminalId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::TransactionNo)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::BusinessDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::CategoryCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::ProductId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::Qty)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::ProductName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::Sku)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::UnitPriceInclTax)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::DiscountPercent)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::PriceBeforeDisc)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::InvoiceNo)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::LineSequence)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::TxnModeCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::IsVatExempt)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::PriceBeforeLessVat)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::IsScpwdDisc)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::OrderedDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::OrderedTime)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::DiscountCode)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::DiscDescription)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::VatableAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::VatAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::LessVat)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::VatExemptAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::ZeroRatedAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::DiscAmt)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::ChargeAmt)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::TotalPortionQty)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(CrrTxnDtl::DiscPortionQty)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-CRR_TXN_DTL-CRR_TXN_HDR")
                            .from(CrrTxnDtl::Table, CrrTxnDtl::CompanyCode)
                            .to(CrrTxnHdr::Table, CrrTxnHdr::CompanyCode)
                            .from_col(CrrTxnDtl::StoreCode)
                            .to_col(CrrTxnHdr::StoreCode)
                            .from_col(CrrTxnDtl::TerminalId)
                            .to_col(CrrTxnHdr::TerminalId)
                            .from_col(CrrTxnDtl::TransactionNo)
                            .to_col(CrrTxnHdr::TransactionNo)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-CRR_TXN_DTL-product_id")
                            .from(CrrTxnDtl::Table, CrrTxnDtl::ProductId)
                            .to(Products::Table, Products::Id)
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(CrrTxnDtl::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum CrrTxnDtl {
    Table,
    Id,
    CompanyCode,
    StoreCode,
    TerminalId,
    TransactionNo,
    BusinessDate,
    CategoryCode,
    ProductId,
    Qty,
    ProductName,
    Sku,
    UnitPriceInclTax,
    DiscountPercent,
    PriceBeforeDisc,
    InvoiceNo,
    LineSequence,
    TxnModeCode,
    IsVatExempt,
    PriceBeforeLessVat,
    IsScpwdDisc,
    OrderedDate,
    OrderedTime,
    DiscountCode,
    DiscDescription,
    VatableAmt,
    VatAmt,
    LessVat,
    VatExemptAmt,
    ZeroRatedAmt,
    DiscAmt,
    ChargeAmt,
    TotalPortionQty,
    DiscPortionQty,
}

#[derive(DeriveIden)]
enum CrrTxnHdr {
    Table,
    CompanyCode,
    StoreCode,
    TerminalId,
    TransactionNo,
}

#[derive(DeriveIden)]
enum Products {
    Table,
    Id,
}
