use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(PosTxnDtl::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(PosTxnDtl::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::CompanyCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::StoreCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::TerminalId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::TransactionNo)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::BusinessDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::CategoryCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::ProductId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::Qty)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::ProductName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::Sku)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::UnitPriceInclTax)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::DiscountPercent)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::PriceBeforeDisc)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::InvoiceNo)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::LineSequence)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::TxnModeCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::IsVatExempt)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::PriceBeforeLessVat)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::IsScpwdDisc)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::OrderedDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::OrderedTime)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::DiscountCode)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::DiscDescription)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::VatableAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::VatAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::LessVat)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::VatExemptAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::ZeroRatedAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::DiscAmt)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::ChargeAmt)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::TotalPortionQty)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(PosTxnDtl::DiscPortionQty)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-POS_TXN_DTL-POS_TXN_HDR")
                            .from(PosTxnDtl::Table, PosTxnDtl::CompanyCode)
                            .to(PosTxnHdr::Table, PosTxnHdr::CompanyCode)
                            .from_col(PosTxnDtl::StoreCode)
                            .to_col(PosTxnHdr::StoreCode)
                            .from_col(PosTxnDtl::TerminalId)
                            .to_col(PosTxnHdr::TerminalId)
                            .from_col(PosTxnDtl::TransactionNo)
                            .to_col(PosTxnHdr::TransactionNo)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk-POS_TXN_DTL-product_id")
                            .from(PosTxnDtl::Table, PosTxnDtl::ProductId) // child
                            .to(Products::Table, Products::Id) // parent
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(PosTxnDtl::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum PosTxnDtl {
    Table,
    Id,
    CompanyCode,
    StoreCode,
    TerminalId,
    TransactionNo,
    BusinessDate,
    CategoryCode,
    ProductId,
    Qty,
    ProductName,
    Sku,
    UnitPriceInclTax,
    DiscountPercent,
    PriceBeforeDisc,
    InvoiceNo,
    LineSequence,
    TxnModeCode,
    IsVatExempt,
    PriceBeforeLessVat,
    IsScpwdDisc,
    OrderedDate,
    OrderedTime,
    DiscountCode,
    DiscDescription,
    VatableAmt,
    VatAmt,
    LessVat,
    VatExemptAmt,
    ZeroRatedAmt,
    DiscAmt,
    ChargeAmt,
    TotalPortionQty,
    DiscPortionQty,
}

#[derive(DeriveIden)]
enum CompanyCode {
    Table,
    CompanyCode,
}

#[derive(DeriveIden)]
enum StoreCode {
    Table,
    StoreCode,
}

#[derive(DeriveIden)]
enum PosTxnHdr {
    Table,
    CompanyCode,
    StoreCode,
    TerminalId,
    TransactionNo,
}

#[derive(DeriveIden)]
enum Products {
    Table,
    Id,
}
    