use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(TempZxReading::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TempZxReading::CompanyCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::StoreCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::TerminalId)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::TransactionNo)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::InvoiceNumber)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::BusinessDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::PaymentType)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::Amount)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::DiscountPct)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::LocalTax)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::ServiceCharge)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::TakeOutCharge)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::DeliveryCharge)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::CardChequeNum)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::CardHolderName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::TraceNo)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::ApprovalCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::TerminalRefNo)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::TransactionType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::VoidTxNum)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::DiscountCode)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::SrPwdId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::OscaPwdName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::IsVatExempt)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::SrPwdVatExemptSale)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::SrPwdTotalAmount)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::SrPwdCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::CashierUserCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::DateStamp)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::TimeStamp)
                            .string()
                            .not_null()
                            .default("00:00:00"),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::VoidedByUserCode)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(TempZxReading::VoidReason)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .primary_key(
                        Index::create()
                            .primary()
                            .col(TempZxReading::CompanyCode)
                            .col(TempZxReading::StoreCode)
                            .col(TempZxReading::TerminalId)
                            .col(TempZxReading::TransactionNo)
                            .col(TempZxReading::BusinessDate)
                            .col(TempZxReading::PaymentType),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(TempZxReading::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum TempZxReading {
    Table,
    CompanyCode,
    StoreCode,
    TerminalId,
    TransactionNo,
    InvoiceNumber,
    BusinessDate,
    PaymentType,
    Amount,
    DiscountPct,
    LocalTax,
    ServiceCharge,
    TakeOutCharge,
    DeliveryCharge,
    CardChequeNum,
    CardHolderName,
    TraceNo,
    ApprovalCode,
    TerminalRefNo,
    TransactionType,
    VoidTxNum,
    DiscountCode,
    SrPwdId,
    OscaPwdName,
    IsVatExempt,
    SrPwdVatExemptSale,
    SrPwdTotalAmount,
    SrPwdCount,
    CashierUserCode,
    DateStamp,
    TimeStamp,
    VoidedByUserCode,
    VoidReason,
}
