use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(TempTxnDtl::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TempTxnDtl::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::CompanyCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::StoreCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::TerminalId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::TransactionNo)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::BusinessDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::CategoryCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::ProductId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::Qty)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::ProductName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::Sku)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::UnitPriceInclTax)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::DiscountPercent)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::PriceBeforeDisc)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::InvoiceNo)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::LineSequence)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::TxnModeCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::IsVatExempt)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::PriceBeforeLessVat)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::IsScpwdDisc)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::OrderedDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::OrderedTime)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::DiscountCode)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::DiscDescription)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::VatableAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::VatAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::LessVat)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::VatExemptAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::ZeroRatedAmt)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::DiscAmt)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::ChargeAmt)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::TotalPortionQty)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(TempTxnDtl::DiscPortionQty)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(TempTxnDtl::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum TempTxnDtl {
    Table,
    Id,
    CompanyCode,
    StoreCode,
    TerminalId,
    TransactionNo,
    BusinessDate,
    CategoryCode,
    ProductId,
    Qty,
    ProductName,
    Sku,
    UnitPriceInclTax,
    DiscountPercent,
    PriceBeforeDisc,
    InvoiceNo,
    LineSequence,
    TxnModeCode,
    IsVatExempt,
    PriceBeforeLessVat,
    IsScpwdDisc,
    OrderedDate,
    OrderedTime,
    DiscountCode,
    DiscDescription,
    VatableAmt,
    VatAmt,
    LessVat,
    VatExemptAmt,
    ZeroRatedAmt,
    DiscAmt,
    ChargeAmt,
    TotalPortionQty,
    DiscPortionQty,
}
