use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(HstZxReading::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(HstZxReading::CompanyCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::StoreCode)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::TerminalId)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::TransactionNo)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::InvoiceNumber)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::BusinessDate)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::PaymentType)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::Amount)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::DiscountPct)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::LocalTax)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::ServiceCharge)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::TakeOutCharge)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::DeliveryCharge)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::CardChequeNum)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::CardHolderName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::TraceNo)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::ApprovalCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::TerminalRefNo)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::TransactionType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::VoidTxNum)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::DiscountCode)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::SrPwdId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::OscaPwdName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::IsVatExempt)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::SrPwdVatExemptSale)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::SrPwdTotalAmount)
                            .decimal()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::SrPwdCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::CashierUserCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::DateStamp)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::TimeStamp)
                            .string()
                            .not_null()
                            .default("00:00:00"),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::VoidedByUserCode)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(HstZxReading::VoidReason)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .primary_key(
                        Index::create()
                            .primary()
                            .col(HstZxReading::CompanyCode)
                            .col(HstZxReading::StoreCode)
                            .col(HstZxReading::TerminalId)
                            .col(HstZxReading::TransactionNo)
                            .col(HstZxReading::BusinessDate)
                            .col(HstZxReading::PaymentType),
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(HstZxReading::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum HstZxReading {
    Table,
    CompanyCode,
    StoreCode,
    TerminalId,
    TransactionNo,
    InvoiceNumber,
    BusinessDate,
    PaymentType,
    Amount,
    DiscountPct,
    LocalTax,
    ServiceCharge,
    TakeOutCharge,
    DeliveryCharge,
    CardChequeNum,
    CardHolderName,
    TraceNo,
    ApprovalCode,
    TerminalRefNo,
    TransactionType,
    VoidTxNum,
    DiscountCode,
    SrPwdId,
    OscaPwdName,
    IsVatExempt,
    SrPwdVatExemptSale,
    SrPwdTotalAmount,
    SrPwdCount,
    CashierUserCode,
    DateStamp,
    TimeStamp,
    VoidedByUserCode,
    VoidReason,
}
